ENV['MOST_CURRENT_CUKE_MODELER_VERSION'] ||= '3'

ENV['CUKE_SLICER_REPORT_FOLDER'] ||= "#{__dir__}/reports"
ENV['CUKE_SLICER_RSPEC_REPORT_NAME'] ||= 'rspec_report'
ENV['CUKE_SLICER_RSPEC_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_SLICER_RSPEC_REPORT_NAME']}.html"
ENV['CUKE_SLICER_CUCUMBER_REPORT_NAME'] ||= 'cucumber_report'
ENV['CUKE_SLICER_CUCUMBER_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_SLICER_CUCUMBER_REPORT_NAME']}.html"
